import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:neo_ledger/update_integrity.dart';

void main() {
  const installerName = 'neo-ledger-windows-1.2.6-setup.exe';
  final bytes = utf8.encode('installer bytes');

  test('finds regular sha256sum entries', () {
    const manifest = '''
# generated by sha256sum
${'a' * 64}  another.zip
${'b' * 64}  $installerName
''';

    expect(findExpectedSha256(manifest, installerName), 'b' * 64);
  });

  test('accepts the binary marker used by sha256sum -b', () {
    final manifest = '${'c' * 64} *$installerName\n';
    expect(findExpectedSha256(manifest, installerName), 'c' * 64);
  });

  test('does not accept a digest belonging to another asset', () {
    final manifest = '${'d' * 64}  another.exe\n';
    expect(findExpectedSha256(manifest, installerName), isNull);
  });

  test('verifies the downloaded bytes and rejects malformed digests', () {
    const expected =
        'e34210a6de4f653edf588301431c3d69a633638cbf587345cc50a7fed9f38f4c';

    expect(verifySha256(bytes: bytes, expected: expected), isTrue);
    expect(verifySha256(bytes: bytes, expected: 'not-a-digest'), isFalse);
  });
}
