export const ACCOUNT_TRANSFERS_TABLE_SQL =
  "CREATE TABLE account_transfers(uuid TEXT PRIMARY KEY,ledger_id INTEGER NOT NULL,kind TEXT NOT NULL,from_account_id INTEGER REFERENCES accounts(id),to_account_id INTEGER REFERENCES accounts(id),amount INTEGER NOT NULL,currency TEXT NOT NULL,target_type TEXT,target_id INTEGER,occurrence_key TEXT,occurred_at TEXT NOT NULL,original_timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai',note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)";

export const ACCOUNT_TRANSFERS_OCCURRENCE_INDEX_SQL =
  "CREATE UNIQUE INDEX account_transfers_occurrence_unique ON account_transfers(occurrence_key) WHERE occurrence_key IS NOT NULL";

export const ACCOUNT_TRANSFERS_LEDGER_INDEX_SQL =
  "CREATE INDEX account_transfers_ledger_time_idx ON account_transfers(ledger_id,occurred_at)";

export const ACCOUNT_TRANSFERS_VALIDATE_TRIGGER_SQL =
  "CREATE TRIGGER account_transfers_validate BEFORE INSERT ON account_transfers WHEN COALESCE((SELECT value FROM app_meta WHERE key='restore_mode'),'0')!='1' BEGIN SELECT CASE WHEN NEW.amount<=0 THEN RAISE(ABORT,'转账金额必须大于零') END; SELECT CASE WHEN NEW.from_account_id IS NULL AND NEW.to_account_id IS NULL THEN RAISE(ABORT,'转账至少需要一个账户') END; SELECT CASE WHEN NEW.from_account_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM accounts WHERE id=NEW.from_account_id AND ledger_id=NEW.ledger_id AND currency=NEW.currency) THEN RAISE(ABORT,'转出账户或币种不匹配') END; SELECT CASE WHEN NEW.to_account_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM accounts WHERE id=NEW.to_account_id AND ledger_id=NEW.ledger_id AND currency=NEW.currency) THEN RAISE(ABORT,'转入账户或币种不匹配') END; SELECT CASE WHEN NEW.from_account_id IS NOT NULL AND (SELECT type FROM accounts WHERE id=NEW.from_account_id)!='资产' AND NEW.kind NOT IN ('余额调账','负债入账') THEN RAISE(ABORT,'转出账户必须是资产账户') END; SELECT CASE WHEN NEW.kind='负债入账' AND (SELECT type FROM accounts WHERE id=NEW.from_account_id)!='负债' THEN RAISE(ABORT,'负债入账必须绑定负债账户') END; SELECT CASE WHEN NEW.from_account_id IS NOT NULL AND (SELECT type FROM accounts WHERE id=NEW.from_account_id)='资产' AND (SELECT current_balance FROM accounts WHERE id=NEW.from_account_id)<NEW.amount THEN RAISE(ABORT,'转出账户余额不足') END; SELECT CASE WHEN NEW.to_account_id IS NOT NULL AND (SELECT type FROM accounts WHERE id=NEW.to_account_id)='负债' AND (SELECT current_balance FROM accounts WHERE id=NEW.to_account_id)+NEW.amount>0 THEN RAISE(ABORT,'还款金额超过当前负债') END; SELECT CASE WHEN NEW.kind='储蓄存入' AND NOT EXISTS(SELECT 1 FROM savings_goals WHERE id=NEW.target_id AND ledger_id=NEW.ledger_id AND saved_amount+NEW.amount<=target_amount) THEN RAISE(ABORT,'存入金额超过心愿剩余目标') END; SELECT CASE WHEN NEW.kind='储蓄退款' AND NOT EXISTS(SELECT 1 FROM savings_goals WHERE id=NEW.target_id AND ledger_id=NEW.ledger_id AND saved_amount>=NEW.amount) THEN RAISE(ABORT,'心愿退款金额无效') END; END";

export const ACCOUNT_TRANSFERS_APPLY_TRIGGER_SQL =
  "CREATE TRIGGER account_transfers_apply AFTER INSERT ON account_transfers WHEN COALESCE((SELECT value FROM app_meta WHERE key='restore_mode'),'0')!='1' BEGIN UPDATE accounts SET current_balance=current_balance-NEW.amount WHERE id=NEW.from_account_id; UPDATE accounts SET current_balance=current_balance+NEW.amount WHERE id=NEW.to_account_id; UPDATE savings_goals SET saved_amount=saved_amount+NEW.amount WHERE id=NEW.target_id AND NEW.kind='储蓄存入'; UPDATE savings_goals SET saved_amount=saved_amount-NEW.amount WHERE id=NEW.target_id AND NEW.kind='储蓄退款'; END";

export const SCHEDULED_OCCURRENCES_TABLE_SQL =
  "CREATE TABLE scheduled_occurrences(occurrence_key TEXT PRIMARY KEY,ledger_id INTEGER NOT NULL,source_type TEXT NOT NULL,source_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT '处理中',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at TEXT)";
