import 'dart:convert';

import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';

import 'models.dart';

class ApiException implements Exception {
  const ApiException(this.message, [this.statusCode]);

  final String message;
  final int? statusCode;

  @override
  String toString() => message;
}

class NeoLedgerApi {
  NeoLedgerApi({FlutterSecureStorage? storage})
    : _storage = storage ?? const FlutterSecureStorage();

  static const _cookieKey = 'neo_ledger_session_cookie';
  static const _baseUrlKey = 'neo_ledger_base_url';
  static const _autoLogSecretKey = 'neo_ledger_auto_log_secret';
  final FlutterSecureStorage _storage;
  String _baseUrl = 'http://localhost:3000';
  String? _cookie;
  String _autoLogSecret = '';

  String get baseUrl => _baseUrl;
  bool get hasSession => _cookie != null && _cookie!.isNotEmpty;
  String get autoLogSecret => _autoLogSecret;

  Future<void> load() async {
    _cookie = await _storage.read(key: _cookieKey);
    _baseUrl = await _storage.read(key: _baseUrlKey) ?? _baseUrl;
    _autoLogSecret = await _storage.read(key: _autoLogSecretKey) ?? '';
  }

  Future<void> setBaseUrl(String value) async {
    final normalized = value.trim().replaceFirst(RegExp(r'/$'), '');
    if (normalized.isEmpty) return;
    _baseUrl = normalized;
    await _storage.write(key: _baseUrlKey, value: normalized);
  }

  /// This is the separate bearer secret generated by the web automatic-ledger
  /// connection. It must never be replaced with the normal login session
  /// cookie: the Android listeners run independently of the Flutter session.
  Future<void> setAutoLogSecret(String value) async {
    _autoLogSecret = value.trim();
    if (_autoLogSecret.isEmpty) {
      await _storage.delete(key: _autoLogSecretKey);
    } else {
      await _storage.write(key: _autoLogSecretKey, value: _autoLogSecret);
    }
  }

  Future<SessionUser> login({
    required String username,
    required String password,
    String? mfaCode,
  }) async {
    final response = await _send(
      'POST',
      '/api/auth',
      body: {
        'action': 'login',
        'username': username,
        'password': password,
        if (mfaCode != null && mfaCode.trim().isNotEmpty)
          'mfaCode': mfaCode.trim(),
      },
      includeCookie: false,
    );
    _saveCookie(response);
    final data = _decode(response);
    final user = data['user'];
    if (user is! Map<String, dynamic>) throw const ApiException('登录响应缺少用户信息');
    return SessionUser.fromJson(user);
  }

  Future<List<Ledger>> fetchLedgers() async {
    final data = await getJson('/api/ledgers');
    return data is List
        ? data.whereType<Map<String, dynamic>>().map(Ledger.fromJson).toList()
        : const [];
  }

  Future<void> saveLedger({
    int? id,
    required String name,
    required String icon,
    String? expectedUpdatedAt,
  }) async {
    final body = <String, dynamic>{
      'name': name.trim(),
      'icon': icon.trim().isEmpty ? '📒' : icon.trim(),
    };
    if (id == null) {
      await postJson('/api/ledgers', body);
      return;
    }
    body['id'] = id;
    body['expectedUpdatedAt'] = expectedUpdatedAt;
    await putJson('/api/ledgers', body);
  }

  Future<void> deleteLedger({
    required int id,
    required String expectedUpdatedAt,
  }) async {
    final path = Uri(
      path: '/api/ledgers',
      queryParameters: {'id': '$id', 'expectedUpdatedAt': expectedUpdatedAt},
    ).toString();
    await _send('DELETE', path);
  }

  Future<List<Account>> fetchAccounts(int ledgerId) async {
    final data = await getJson('/api/accounts?ledger=$ledgerId');
    return data is List
        ? data.whereType<Map<String, dynamic>>().map(Account.fromJson).toList()
        : const [];
  }

  Future<List<Member>> fetchMembers(int ledgerId) async {
    final data = await getJson('/api/members?ledger=$ledgerId');
    return data is List
        ? data.whereType<Map<String, dynamic>>().map(Member.fromJson).toList()
        : const [];
  }

  Future<List<Category>> fetchCategories(
    int ledgerId, {
    required bool income,
  }) async {
    final path = income
        ? '/api/income-categories?ledger=$ledgerId'
        : '/api/categories?ledger=$ledgerId';
    final data = await getJson(path);
    return data is List
        ? data.whereType<Map<String, dynamic>>().map(Category.fromJson).toList()
        : const [];
  }

  Future<void> saveCategory({
    int? id,
    required int ledgerId,
    required bool income,
    required String name,
    required String icon,
    required String color,
    bool? isActive,
  }) async {
    final path = income ? '/api/income-categories' : '/api/categories';
    final body = <String, dynamic>{
      'ledgerId': ledgerId,
      'name': name.trim(),
      'icon': icon.trim().isEmpty ? '🧾' : icon.trim(),
      'color': color.trim().isEmpty ? '#6B7280' : color.trim(),
    };
    if (id == null) {
      await postJson(path, body);
      return;
    }
    body['id'] = id;
    if (isActive != null) body['isActive'] = isActive;
    await putJson(path, body);
  }

  Future<void> deleteCategory({
    required int id,
    required int ledgerId,
    required bool income,
  }) async {
    final path = income ? '/api/income-categories' : '/api/categories';
    final query = Uri(
      path: path,
      queryParameters: {'id': '$id', 'ledger': '$ledgerId'},
    ).toString();
    await _send('DELETE', query);
  }

  Future<Preferences> fetchPreferences() async {
    final data = await getJson('/api/preferences');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('隐私配置响应格式无效');
    }
    return Preferences.fromJson(data);
  }

  Future<void> updatePreferences({
    String? theme,
    bool? enabled,
    String? pin,
  }) async {
    final body = <String, dynamic>{};
    if (theme != null) body['theme'] = theme;
    if (enabled != null) body['enabled'] = enabled;
    if (pin != null && pin.trim().isNotEmpty) body['pin'] = pin.trim();
    await patchJson('/api/preferences', body);
  }

  Future<bool> verifyPreferencesPin(String pin) async {
    try {
      final data = await postJson('/api/preferences', {'pin': pin});
      return data is Map<String, dynamic> && data['ok'] == true;
    } on ApiException catch (error) {
      if (error.statusCode == 401 || error.statusCode == 403) return false;
      rethrow;
    }
  }

  Future<AiReply> askAi({
    required int ledgerId,
    required String message,
    required bool consentExternal,
  }) async {
    final data = await postJson(
      '/api/v1/ai/chat',
      {'ledgerId': ledgerId, 'message': message.trim()},
      extraHeaders: {'x-neo-ai-consent': consentExternal ? 'true' : 'false'},
    );
    if (data is! Map<String, dynamic>) throw const ApiException('AI 响应格式无效');
    return AiReply.fromJson(data);
  }

  Future<Map<String, dynamic>> syncWebDav({
    required String action,
    required String url,
    required String username,
    required String password,
    String? payload,
  }) async {
    final body = <String, dynamic>{
      'action': action,
      'url': url.trim(),
      'username': username.trim(),
      'password': password,
    };
    if (payload != null) body['payload'] = payload;
    final data = await postJson('/api/webdav-sync', body);
    if (data is! Map<String, dynamic>) {
      throw const ApiException('WebDAV 响应格式无效');
    }
    return data;
  }

  Future<Map<String, dynamic>> fetchP2pStatus() async {
    final data = await getJson('/api/p2p/discovery');
    if (data is! Map<String, dynamic>) throw const ApiException('P2P 状态响应格式无效');
    return data;
  }

  Future<ExchangeRateSnapshot> fetchExchangeRates() async {
    final data = await getJson('/api/exchange-rates');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('汇率响应格式无效');
    }
    return ExchangeRateSnapshot.fromJson(data);
  }

  Future<List<AutomationRule>> fetchAutomationRules(int ledgerId) async {
    final data = await getJson('/api/automation/rules?ledger=$ledgerId');
    if (data is! List) throw const ApiException('自动化规则响应格式无效');
    return data
        .whereType<Map<String, dynamic>>()
        .map(AutomationRule.fromJson)
        .toList();
  }

  Future<void> createAutomationRule({
    required int ledgerId,
    required String name,
    required int priority,
    required bool enabled,
    required Map<String, dynamic> conditions,
    required Map<String, dynamic> actions,
  }) async {
    await postJson('/api/automation/rules', {
      'ledgerId': ledgerId,
      'name': name.trim(),
      'priority': priority,
      'enabled': enabled,
      'conditions': conditions,
      'actions': actions,
    });
  }

  Future<void> updateAutomationRule({
    required String id,
    required int ledgerId,
    String? name,
    int? priority,
    bool? enabled,
    Map<String, dynamic>? conditions,
    Map<String, dynamic>? actions,
  }) async {
    final body = <String, dynamic>{'id': id, 'ledgerId': ledgerId};
    if (name != null) body['name'] = name.trim();
    if (priority != null) body['priority'] = priority;
    if (enabled != null) body['enabled'] = enabled;
    if (conditions != null) body['conditions'] = conditions;
    if (actions != null) body['actions'] = actions;
    await patchJson('/api/automation/rules', body);
  }

  Future<void> deleteAutomationRule({
    required String id,
    required int ledgerId,
  }) async {
    await deleteJson('/api/automation/rules', {
      'id': id,
      'ledgerId': ledgerId,
    });
  }

  Future<QuickSyncStatus> fetchQuickSyncStatus() async {
    final data = await getJson('/api/integrations/quick-sync');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('快捷同步响应格式无效');
    }
    return QuickSyncStatus.fromJson(data);
  }

  Future<String> createQuickSyncToken({
    required String label,
    required int expiresInDays,
    required String scope,
  }) async {
    final data = await postJson('/api/integrations/quick-sync', {
      'label': label.trim(),
      'expiresInDays': expiresInDays,
      'scope': scope,
    });
    if (data is Map<String, dynamic> && data['token'] is String) {
      final token = (data['token'] as String).trim();
      if (token.isNotEmpty) return token;
    }
    throw const ApiException('快捷同步未返回一次性密钥');
  }

  Future<void> revokeQuickSyncToken() async {
    await _send('DELETE', '/api/integrations/quick-sync');
  }

  Future<List<SecuritySession>> fetchSecuritySessions() async {
    final data = await getJson('/api/security/sessions');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('登录会话响应格式无效');
    }
    return (data['sessions'] as List<dynamic>? ?? const [])
        .whereType<Map<String, dynamic>>()
        .map(SecuritySession.fromJson)
        .toList();
  }

  Future<void> revokeSecuritySession({
    String? sessionId,
    bool allExceptCurrent = false,
  }) async {
    final body = <String, dynamic>{};
    if (sessionId != null && sessionId.trim().isNotEmpty) {
      body['sessionId'] = sessionId.trim();
    } else if (allExceptCurrent) {
      body['allExceptCurrent'] = true;
    } else {
      throw const ApiException('缺少要撤销的会话');
    }
    await deleteJson('/api/security/sessions', body);
  }

  Future<SecurityAuditPage> fetchSecurityAudit() async {
    final data = await getJson('/api/security/audit?limit=100');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('安全审计响应格式无效');
    }
    return SecurityAuditPage.fromJson(data);
  }

  Future<Member> createMember({
    required int ledgerId,
    required String name,
    required String icon,
  }) async {
    final data = await postJson('/api/members', {
      'ledgerId': ledgerId,
      'name': name.trim(),
      'icon': icon.trim().isEmpty ? '👤' : icon.trim(),
    });
    if (data is! Map<String, dynamic>) throw const ApiException('参与人响应格式无效');
    return Member.fromJson(data);
  }

  Future<void> settleMember({
    required int ledgerId,
    required int memberId,
    required double amount,
    required String direction,
  }) async {
    await postJson('/api/settlements', {
      'ledgerId': ledgerId,
      'memberId': memberId,
      'amount': (amount * 100).round(),
      'direction': direction,
      'idempotencyKey': _idempotencyKey('native-settlement'),
    });
  }

  Future<void> saveFireSettings({
    required int ledgerId,
    required double monthlyExpense,
    required double annualReturn,
  }) async {
    await putJson('/api/fire-settings', {
      'ledgerId': ledgerId,
      'monthlyExpense': monthlyExpense,
      'annualReturn': annualReturn,
    });
  }

  Future<Map<String, dynamic>> fetchFireSettings(int ledgerId) async {
    final data = await getJson('/api/fire-settings?ledger=$ledgerId');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('FIRE 参数响应格式无效');
    }
    return data;
  }

  Future<void> saveEconomicSettings({
    required int ledgerId,
    required double inflationRate,
  }) async {
    await putJson('/api/economic-settings', {
      'ledgerId': ledgerId,
      'inflationRate': inflationRate,
    });
  }

  Future<Map<String, dynamic>> fetchEconomicSettings(int ledgerId) async {
    final data = await getJson('/api/economic-settings?ledger=$ledgerId');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('经济参数响应格式无效');
    }
    return data;
  }

  Future<void> saveAccount({
    int? id,
    required int ledgerId,
    required String name,
    required String type,
    required double balance,
    int? billDay,
    int? repaymentDay,
    required bool isInvestment,
    required String currency,
    required String assetClass,
    String? expectedUpdatedAt,
  }) async {
    final body = <String, dynamic>{
      'ledgerId': ledgerId,
      'name': name.trim(),
      'type': type,
      'balance': balance,
      'billDay': billDay,
      'repaymentDay': repaymentDay,
      'isInvestment': isInvestment,
      'currency': currency,
      'assetClass': assetClass,
    };
    if (id == null) {
      await postJson('/api/accounts', body);
      return;
    }
    body['id'] = id;
    body['expectedUpdatedAt'] = expectedUpdatedAt;
    await putJson('/api/accounts', body);
  }

  Future<void> deleteAccount({
    required int id,
    required String expectedUpdatedAt,
  }) async {
    final path = Uri(
      path: '/api/accounts',
      queryParameters: {'id': '$id', 'expectedUpdatedAt': expectedUpdatedAt},
    ).toString();
    await _send('DELETE', path);
  }

  Future<void> transfer({
    required int ledgerId,
    required String kind,
    required int fromAccountId,
    required int toAccountId,
    required double amount,
    required String occurredAt,
    required String originalTimezone,
    String? note,
  }) async {
    await postJson('/api/transfers', {
      'ledgerId': ledgerId,
      'kind': kind,
      'fromAccountId': fromAccountId,
      'toAccountId': toAccountId,
      'amount': amount,
      'idempotencyKey': _idempotencyKey('native-transfer'),
      'occurredAt': occurredAt,
      'originalTimezone': originalTimezone,
      if (note != null && note.trim().isNotEmpty) 'note': note.trim(),
    });
  }

  Future<TransactionPage> fetchTransactions(int ledgerId) async {
    final data = await getJson(
      '/api/transactions/query?ledger=$ledgerId&limit=50',
    );
    if (data is! Map<String, dynamic>) throw const ApiException('流水响应格式无效');
    return TransactionPage.fromJson(data);
  }

  Future<AnalysisSummary> fetchAnalysis(int ledgerId) async {
    final now = DateTime.now();
    final today =
        '${now.year.toString().padLeft(4, '0')}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';
    final query = [
      'ledger=$ledgerId',
      'today=$today',
      'dimension=%E6%9C%88',
      'offset=${now.timeZoneOffset.inMinutes}',
      'hour=${now.hour}',
      'now=${Uri.encodeQueryComponent(now.toUtc().toIso8601String())}',
    ].join('&');
    final data = await getJson('/api/transactions/summary?$query');
    if (data is! Map<String, dynamic>) throw const ApiException('分析响应格式无效');
    return AnalysisSummary.fromJson(data);
  }

  Future<List<CategoryBudget>> fetchBudgets(int ledgerId) async {
    final data = await getJson('/api/category-budgets?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(CategoryBudget.fromJson)
              .toList()
        : const [];
  }

  Future<void> saveCategoryBudget({
    required int ledgerId,
    required String category,
    required double amount,
  }) async {
    await putJson('/api/category-budgets', {
      'ledgerId': ledgerId,
      'category': category.trim(),
      'amount': amount,
    });
  }

  Future<List<Subscription>> fetchSubscriptions(int ledgerId) async {
    final data = await getJson('/api/subscriptions?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(Subscription.fromJson)
              .toList()
        : const [];
  }

  Future<List<Installment>> fetchInstallments(int ledgerId) async {
    final data = await getJson('/api/installments?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(Installment.fromJson)
              .toList()
        : const [];
  }

  Future<List<SavingsGoal>> fetchSavingsGoals(int ledgerId) async {
    final data = await getJson('/api/savings-goals?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(SavingsGoal.fromJson)
              .toList()
        : const [];
  }

  Future<Forecast> fetchForecast(int ledgerId) async {
    final data = await getJson('/api/forecast?ledger=$ledgerId');
    if (data is! Map<String, dynamic>) throw const ApiException('现金流预测响应格式无效');
    return Forecast.fromJson(data);
  }

  Future<List<DigitalAsset>> fetchAssets(int ledgerId) async {
    final data = await getJson('/api/assets?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(DigitalAsset.fromJson)
              .toList()
        : const [];
  }

  Future<void> saveAsset({
    int? id,
    required int ledgerId,
    required String name,
    required String assetType,
    required String currency,
    required String valuationMode,
    required double manualValue,
    required double purchasePrice,
    required String purchaseDate,
    required int lifespanMonths,
    required double residualRate,
    String? heatLevel,
    String? expectedUpdatedAt,
  }) async {
    final body = <String, dynamic>{
      'ledgerId': ledgerId,
      'name': name.trim(),
      'assetType': assetType,
      'currency': currency,
      'valuationMode': valuationMode,
      'manualValue': manualValue,
      'purchasePrice': purchasePrice,
      'purchaseDate': purchaseDate,
      'lifespanMonths': lifespanMonths,
      'residualRate': residualRate,
    };
    if (heatLevel != null) body['heatLevel'] = heatLevel;
    if (id != null) body['id'] = id;
    if (expectedUpdatedAt != null) {
      body['expectedUpdatedAt'] = expectedUpdatedAt;
    }
    if (id == null) {
      await postJson('/api/assets', body);
    } else {
      await putJson('/api/assets', body);
    }
  }

  Future<void> liquidateAsset({
    required int id,
    required int ledgerId,
    required double salePrice,
    required int accountId,
    required String expectedUpdatedAt,
  }) async {
    await patchJson('/api/assets', {
      'id': id,
      'ledgerId': ledgerId,
      'salePrice': salePrice,
      'accountId': accountId,
      'expectedUpdatedAt': expectedUpdatedAt,
      'idempotencyKey': _idempotencyKey('native-liquidation'),
    });
  }

  String _idempotencyKey(String prefix) {
    return '$prefix-${DateTime.now().microsecondsSinceEpoch}';
  }

  Future<void> saveSubscription({
    int? id,
    required int ledgerId,
    required String name,
    required double amount,
    required int accountId,
    required String cycle,
    required String category,
    required String nextChargeDate,
  }) async {
    final body = <String, dynamic>{
      'ledgerId': ledgerId,
      'name': name.trim(),
      'amount': amount,
      'accountId': accountId,
      'cycle': cycle,
      'category': category.trim(),
      'nextChargeDate': nextChargeDate,
    };
    if (id == null) {
      await postJson('/api/subscriptions', body);
    } else {
      body['id'] = id;
      await putJson('/api/subscriptions', body);
    }
  }

  Future<void> deleteSubscription({
    required int id,
    required int ledgerId,
  }) async {
    final path = Uri(
      path: '/api/subscriptions',
      queryParameters: {'id': '$id', 'ledger': '$ledgerId'},
    ).toString();
    await _send('DELETE', path);
  }

  Future<void> createInstallment({
    required int ledgerId,
    required String name,
    required double totalAmount,
    required int periods,
    required double feeAmount,
    required int accountId,
    required int paymentAccountId,
    required String startMonth,
    required int chargeDay,
  }) async {
    await postJson('/api/installments', {
      'ledgerId': ledgerId,
      'name': name.trim(),
      'totalAmount': totalAmount,
      'periods': periods,
      'feeAmount': feeAmount,
      'accountId': accountId,
      'paymentAccountId': paymentAccountId,
      'startMonth': startMonth,
      'chargeDay': chargeDay,
      'idempotencyKey': _idempotencyKey('native-installment'),
    });
  }

  Future<void> deleteInstallment({
    required int id,
    required String expectedUpdatedAt,
  }) async {
    final path = Uri(
      path: '/api/installments',
      queryParameters: {
        'id': '$id',
        'expectedUpdatedAt': expectedUpdatedAt,
        'idempotencyKey': _idempotencyKey('native-installment-delete'),
      },
    ).toString();
    await _send('DELETE', path);
  }

  Future<void> createSavingsGoal({
    required int ledgerId,
    required String name,
    required double targetAmount,
    required String deadline,
    required String icon,
  }) async {
    await postJson('/api/savings-goals', {
      'ledgerId': ledgerId,
      'name': name.trim(),
      'targetAmount': targetAmount,
      'deadline': deadline,
      'icon': icon.trim().isEmpty ? '🌟' : icon.trim(),
    });
  }

  Future<void> contributeSavingsGoal({
    required int id,
    required int accountId,
    required double amount,
  }) async {
    await patchJson('/api/savings-goals', {
      'id': id,
      'accountId': accountId,
      'amount': amount,
      'idempotencyKey': _idempotencyKey('native-goal-contribution'),
    });
  }

  Future<void> deleteSavingsGoal({
    required int id,
    required int accountId,
    required String expectedUpdatedAt,
  }) async {
    await deleteJson('/api/savings-goals', {
      'id': id,
      'accountId': accountId,
      'expectedUpdatedAt': expectedUpdatedAt,
      'idempotencyKey': _idempotencyKey('native-goal-delete'),
    });
  }

  Future<List<NotificationItem>> fetchNotifications(int ledgerId) async {
    final data = await getJson('/api/notifications?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(NotificationItem.fromJson)
              .toList()
        : const [];
  }

  Future<PendingTransactionPage> fetchPendingTransactions(int ledgerId) async {
    final response = await _send(
      'GET',
      '/api/pending-transactions?ledger=$ledgerId&limit=100',
    );
    final data = _decodeAny(response);
    if (data is! Map<String, dynamic>) {
      throw const ApiException('待处理账单响应格式无效');
    }
    return PendingTransactionPage(
      items: (data['items'] as List<dynamic>? ?? const [])
          .whereType<Map<String, dynamic>>()
          .map(PendingTransaction.fromJson)
          .toList(),
      total:
          int.tryParse(response.headers['x-total-count'] ?? '') ??
          int.tryParse('${data['total'] ?? 0}') ??
          0,
      hasMore:
          response.headers['x-has-more'] == 'true' || data['hasMore'] == true,
    );
  }

  Future<void> markNotificationsRead(int ledgerId) async {
    await patchJson('/api/notifications', {'ledgerId': ledgerId});
  }

  Future<void> resolvePendingTransaction(
    int id, {
    required String action,
    String? category,
  }) async {
    await patchJson('/api/pending-transactions', {
      'id': id,
      'action': action,
      if (category != null && category.trim().isNotEmpty)
        'category': category.trim(),
    });
  }

  Future<void> updateTransaction(
    TransactionItem item, {
    required String title,
    required double amount,
    required String type,
    required int accountId,
    required String category,
    String? mood,
  }) async {
    if (item.ledgerId <= 0 || item.updatedAt == null) {
      throw const ApiException('流水缺少版本信息，请刷新后再编辑');
    }
    final occurred = DateTime.tryParse(item.occurredAt)?.toLocal();
    if (occurred == null) throw const ApiException('流水时间格式无效');
    final localDate = DateFormat("yyyy-MM-dd'T'HH:mm").format(occurred);
    await putJson('/api/transactions', {
      'id': item.id,
      'ledgerId': item.ledgerId,
      'accountId': accountId,
      'amount': amount,
      'type': type,
      'title': title,
      'mood': mood ?? item.mood ?? '刚需',
      'category': type == '支出' ? category : '其它',
      'incomeCategory': type == '收入' ? category : '其它收入',
      'occurredAt': localDate,
      'originalTimezone': item.originalTimezone,
      'expectedUpdatedAt': item.updatedAt,
    });
  }

  Future<Map<String, dynamic>> previewBillImport({
    required int ledgerId,
    required List<Map<String, dynamic>> items,
  }) async {
    final data = await postJson('/api/bill-import', {
      'ledgerId': ledgerId,
      'items': items,
    });
    if (data is! Map<String, dynamic>) throw const ApiException('账单预检响应格式无效');
    return data;
  }

  Future<Map<String, dynamic>> importBills({
    required int ledgerId,
    required List<Map<String, dynamic>> items,
  }) async {
    final data = await putJson('/api/bill-import', {
      'ledgerId': ledgerId,
      'items': items,
    });
    if (data is! Map<String, dynamic>) throw const ApiException('账单导入响应格式无效');
    return data;
  }

  Future<void> deleteTransaction(TransactionItem item) async {
    if (item.ledgerId <= 0 || item.updatedAt == null) {
      throw const ApiException('流水缺少版本信息，请刷新后再删除');
    }
    await deleteJson('/api/transactions', {
      'id': item.id,
      'ledgerId': item.ledgerId,
      'expectedUpdatedAt': item.updatedAt,
    });
  }

  Future<List<String>> syncEntries(List<OfflineEntry> entries) async {
    if (entries.isEmpty) return const [];
    final data = await postJson('/api/offline-sync', {
      'items': entries.map((entry) => entry.toJson()).toList(),
    });
    if (data is! Map<String, dynamic>) throw const ApiException('同步响应格式无效');
    return (data['synced'] as List<dynamic>? ?? const [])
        .map((value) => '$value')
        .toList();
  }

  /// Exports the complete server-side backup as the JSON document produced by
  /// `/api/data/export`. Keeping the raw document lets the native client pass
  /// it back to the restore endpoint without losing fields added by the web
  /// client in a newer backup schema.
  Future<String> exportBackup() async {
    final response = await _send('GET', '/api/data/export');
    return utf8.decode(response.bodyBytes);
  }

  /// Runs the server's validation-only or actual restore flow.
  Future<Map<String, dynamic>> restoreBackup(
    String rawBackup, {
    required bool dryRun,
    String? expectedPlanChecksum,
  }) async {
    final decoded = jsonDecode(rawBackup);
    if (decoded is! Map) throw const ApiException('备份必须是 JSON 对象');
    final body = Map<String, dynamic>.from(decoded);
    body['dryRun'] = dryRun;
    final response = await _send(
      'POST',
      '/api/data/restore',
      body: body,
      extraHeaders: {
        if (expectedPlanChecksum != null && expectedPlanChecksum.isNotEmpty)
          'x-restore-plan-checksum': expectedPlanChecksum,
      },
    );
    final data = _decodeAny(response);
    if (data is! Map<String, dynamic>) {
      throw const ApiException('恢复响应格式无效');
    }
    return data;
  }

  Future<dynamic> getJson(String path) async =>
      _decodeAny(await _send('GET', path));

  Future<dynamic> postJson(
    String path,
    Map<String, dynamic> body, {
    Map<String, String>? extraHeaders,
  }) async => _decodeAny(
    await _send('POST', path, body: body, extraHeaders: extraHeaders),
  );

  Future<dynamic> putJson(String path, Map<String, dynamic> body) async =>
      _decodeAny(await _send('PUT', path, body: body));

  Future<dynamic> patchJson(String path, Map<String, dynamic> body) async =>
      _decodeAny(await _send('PATCH', path, body: body));

  Future<dynamic> deleteJson(String path, Map<String, dynamic> body) async =>
      _decodeAny(await _send('DELETE', path, body: body));

  Future<http.Response> _send(
    String method,
    String path, {
    Map<String, dynamic>? body,
    bool includeCookie = true,
    Map<String, String>? extraHeaders,
  }) async {
    final uri = Uri.parse('$_baseUrl$path');
    final headers = <String, String>{
      'Accept': 'application/json',
      'Cache-Control': 'no-cache',
    };
    if (extraHeaders != null) headers.addAll(extraHeaders);
    if (body != null) headers['Content-Type'] = 'application/json';
    if (includeCookie && hasSession) headers['Cookie'] = _cookie!;
    try {
      final response = switch (method) {
        'POST' => await http.post(
          uri,
          headers: headers,
          body: body == null ? null : jsonEncode(body),
        ),
        'PUT' => await http.put(
          uri,
          headers: headers,
          body: body == null ? null : jsonEncode(body),
        ),
        'PATCH' => await http.patch(
          uri,
          headers: headers,
          body: body == null ? null : jsonEncode(body),
        ),
        'DELETE' => await http.delete(
          uri,
          headers: headers,
          body: body == null ? null : jsonEncode(body),
        ),
        _ => await http.get(uri, headers: headers),
      };
      if (response.statusCode < 200 || response.statusCode >= 300) {
        throw ApiException(_errorMessage(response), response.statusCode);
      }
      return response;
    } on ApiException {
      rethrow;
    } catch (error) {
      throw ApiException('无法连接 $_baseUrl：$error');
    }
  }

  Map<String, dynamic> _decode(http.Response response) {
    final value = _decodeAny(response);
    if (value is! Map<String, dynamic>) throw const ApiException('服务器响应格式无效');
    return value;
  }

  dynamic _decodeAny(http.Response response) {
    try {
      return jsonDecode(utf8.decode(response.bodyBytes));
    } catch (_) {
      throw const ApiException('服务器返回了无法解析的数据');
    }
  }

  String _errorMessage(http.Response response) {
    try {
      final decoded = jsonDecode(utf8.decode(response.bodyBytes));
      if (decoded is Map<String, dynamic>) {
        return '${decoded['error'] ?? decoded['message'] ?? '请求失败'}';
      }
    } catch (_) {}
    return '请求失败（HTTP ${response.statusCode}）';
  }

  void _saveCookie(http.Response response) {
    final raw = response.headers['set-cookie'];
    if (raw == null) return;
    final match = RegExp(r'(neo_ledger_session=[^;]+)').firstMatch(raw);
    if (match == null) return;
    _cookie = match.group(1);
    _storage.write(key: _cookieKey, value: _cookie);
  }

  Future<void> logout() async {
    _cookie = null;
    await _storage.delete(key: _cookieKey);
  }
}
