import 'dart:convert';

import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:intl/intl.dart';

import 'mobile/data/mobile_api_transport.dart';
import 'mobile/data/mobile_api_session_store.dart';
import 'mobile/data/mobile_idempotency_key_store.dart';
import 'mobile/domain/mobile_api_exception.dart';
import 'models.dart';

export 'mobile/domain/mobile_api_exception.dart' show ApiException;

class NeoLedgerApi {
  factory NeoLedgerApi({
    MobileApiSessionStore? session,
    MobileIdempotencyKeyStore? idempotencyKeys,
    MobileApiTransport? transport,
  }) {
    final sessionStore =
        session ??
        transport?.session ??
        MobileApiSessionStore.secure(const FlutterSecureStorage());
    final keyStore =
        idempotencyKeys ??
        MobileIdempotencyKeyStore.secure(const FlutterSecureStorage());
    return NeoLedgerApi._(
      session: sessionStore,
      idempotencyKeys: keyStore,
      transport:
          transport ??
          MobileApiTransport(session: sessionStore, idempotencyKeys: keyStore),
    );
  }

  NeoLedgerApi._({
    required this._session,
    required this._idempotencyKeys,
    required this._transport,
  });

  final MobileApiSessionStore _session;
  final MobileIdempotencyKeyStore _idempotencyKeys;
  final MobileApiTransport _transport;
  // Native mobile builds talk to the same hosted account as the web client.
  // A user can still override this through the persisted server setting.

  String get baseUrl => _session.baseUrl;
  bool get hasSession => _session.hasSession;
  String get autoLogSecret => _session.autoLogSecret;

  Future<void> load() => _session.load();

  Future<SessionUser?> fetchSessionUser() async {
    final data = await getJson('/api/auth');
    if (data is! Map<String, dynamic> || data['authenticated'] != true) {
      return null;
    }
    final rawUser = data['user'];
    if (rawUser is! Map) throw const ApiException('账号状态响应缺少用户信息');
    return SessionUser.fromJson(Map<String, dynamic>.from(rawUser));
  }

  Future<String?> updateAvatar(String? dataUrl) async {
    final data = await patchJson('/api/auth', {'avatarUrl': dataUrl});
    if (data is! Map<String, dynamic>) {
      throw const ApiException('头像响应格式无效');
    }
    return data['avatarUrl'] as String?;
  }

  Future<String> updateDisplayName(String displayName) async {
    final data = await patchJson('/api/auth', {
      'displayName': displayName.trim(),
    });
    if (data is! Map<String, dynamic> || data['displayName'] is! String) {
      throw const ApiException('昵称更新响应格式无效');
    }
    return data['displayName'] as String;
  }

  Future<void> bindAccountEmail({
    required String email,
    required String code,
    String? currentPassword,
    String? newPassword,
  }) async {
    await patchJson('/api/auth', {
      'email': email.trim(),
      'code': code.trim(),
      if (currentPassword != null && currentPassword.isNotEmpty)
        'currentPassword': currentPassword,
      if (newPassword != null && newPassword.isNotEmpty)
        'newPassword': newPassword,
    });
  }

  Future<void> setBaseUrl(String value) => _session.setBaseUrl(value);

  /// This is the separate bearer secret generated by the web automatic-ledger
  /// connection. It must never be replaced with the normal login session
  /// cookie: the Android listeners run independently of the Flutter session.
  Future<void> setAutoLogSecret(String value) =>
      _session.setAutoLogSecret(value);

  Future<SessionUser> login({
    required String username,
    required String password,
    String? mfaCode,
  }) async {
    final response = await _transport.send(
      'POST',
      '/api/auth',
      body: {
        'action': 'login',
        'username': username,
        'password': password,
        if (mfaCode != null && mfaCode.trim().isNotEmpty)
          'mfaCode': mfaCode.trim(),
      },
      includeCookie: false,
    );
    await _session.captureSetCookieHeader(response.headers['set-cookie']);
    final data = _transport.decodeObject(response);
    final user = data['user'];
    if (user is! Map<String, dynamic>) throw const ApiException('登录响应缺少用户信息');
    return SessionUser.fromJson(user);
  }

  Future<SessionUser> register({
    required String username,
    required String email,
    required String displayName,
    required String password,
    String? code,
  }) async {
    final response = await _transport.send(
      'POST',
      '/api/auth',
      body: {
        'action': 'register',
        'username': username.trim(),
        'email': email.trim(),
        'displayName': displayName.trim(),
        'password': password,
        if (code != null && code.trim().isNotEmpty) 'code': code.trim(),
      },
      includeCookie: false,
    );
    await _session.captureSetCookieHeader(response.headers['set-cookie']);
    final data = _transport.decodeObject(response);
    final user = data['user'];
    if (user is! Map<String, dynamic>) {
      throw const ApiException('注册响应缺少用户信息');
    }
    return SessionUser.fromJson(user);
  }

  Future<void> requestEmailCode({
    required String email,
    required String purpose,
  }) async {
    await postJson('/api/auth/email-code', {
      'email': email.trim(),
      'purpose': purpose,
    });
  }

  Future<void> resetPassword({
    required String email,
    required String code,
    required String newPassword,
  }) async {
    await postJson('/api/auth/reset-password', {
      'email': email.trim(),
      'code': code.trim(),
      'newPassword': newPassword,
    });
  }

  Future<List<Ledger>> fetchLedgers() async {
    final data = await getJson('/api/ledgers');
    return data is List
        ? data.whereType<Map<String, dynamic>>().map(Ledger.fromJson).toList()
        : const [];
  }

  Future<void> saveLedger({
    int? id,
    required String name,
    required String icon,
    String? expectedUpdatedAt,
  }) async {
    final body = <String, dynamic>{
      'name': name.trim(),
      'icon': icon.trim().isEmpty ? '📒' : icon.trim(),
    };
    if (id == null) {
      await postJson('/api/ledgers', body);
      return;
    }
    body['id'] = id;
    body['expectedUpdatedAt'] = expectedUpdatedAt;
    await putJson('/api/ledgers', body);
  }

  Future<void> deleteLedger({
    required int id,
    required String expectedUpdatedAt,
  }) async {
    final path = Uri(
      path: '/api/ledgers',
      queryParameters: {'id': '$id', 'expectedUpdatedAt': expectedUpdatedAt},
    ).toString();
    await _transport.send('DELETE', path);
  }

  Future<List<Account>> fetchAccounts(int ledgerId) async {
    final data = await getJson('/api/accounts?ledger=$ledgerId');
    return data is List
        ? data.whereType<Map<String, dynamic>>().map(Account.fromJson).toList()
        : const [];
  }

  Future<List<AccountTransfer>> fetchAccountTransfers({
    required int ledgerId,
    required int accountId,
  }) async {
    final query = Uri(
      queryParameters: {'ledger': '$ledgerId', 'account': '$accountId'},
    ).query;
    final data = await getJson('/api/transfers?$query');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(AccountTransfer.fromJson)
              .toList()
        : const [];
  }

  Future<void> updateAccountTransfer({
    required String uuid,
    required int ledgerId,
    required String expectedUpdatedAt,
    required String kind,
    required int fromAccountId,
    required int toAccountId,
    required double amount,
    required String occurredAt,
    required String originalTimezone,
    required String note,
  }) async {
    await putJson('/api/transfers', {
      'uuid': uuid,
      'ledgerId': ledgerId,
      'expectedUpdatedAt': expectedUpdatedAt,
      'kind': kind,
      'fromAccountId': fromAccountId,
      'toAccountId': toAccountId,
      'amount': amount,
      'occurredAt': occurredAt,
      'originalTimezone': originalTimezone,
      'note': note,
    });
  }

  Future<void> deleteAccountTransfer({
    required String uuid,
    required int ledgerId,
    required String expectedUpdatedAt,
  }) async {
    final path = Uri(
      path: '/api/transfers',
      queryParameters: {
        'uuid': uuid,
        'ledger': '$ledgerId',
        'expectedUpdatedAt': expectedUpdatedAt,
      },
    ).toString();
    await _transport.send('DELETE', path);
  }

  Future<List<Member>> fetchMembers(int ledgerId) async {
    final data = await getJson('/api/members?ledger=$ledgerId');
    return data is List
        ? data.whereType<Map<String, dynamic>>().map(Member.fromJson).toList()
        : const [];
  }

  Future<List<Category>> fetchCategories(
    int ledgerId, {
    required bool income,
  }) async {
    final path = income
        ? '/api/income-categories?ledger=$ledgerId'
        : '/api/categories?ledger=$ledgerId';
    final data = await getJson(path);
    return data is List
        ? data.whereType<Map<String, dynamic>>().map(Category.fromJson).toList()
        : const [];
  }

  Future<void> saveCategory({
    int? id,
    required int ledgerId,
    required bool income,
    required String name,
    required String icon,
    required String color,
    bool? isActive,
    int? parentId,
  }) async {
    final path = income ? '/api/income-categories' : '/api/categories';
    final body = <String, dynamic>{
      'ledgerId': ledgerId,
      'name': name.trim(),
      'icon': icon.trim().isEmpty ? '🧾' : icon.trim(),
      'color': color.trim().isEmpty ? '#6B7280' : color.trim(),
    };
    if (id == null) {
      if (parentId != null) body['parentId'] = parentId;
      await postJson(path, body);
      return;
    }
    body['id'] = id;
    if (isActive != null) body['isActive'] = isActive;
    body['parentId'] = parentId;
    await putJson(path, body);
  }

  Future<void> deleteCategory({
    required int id,
    required int ledgerId,
    required bool income,
  }) async {
    final path = income ? '/api/income-categories' : '/api/categories';
    final query = Uri(
      path: path,
      queryParameters: {'id': '$id', 'ledger': '$ledgerId'},
    ).toString();
    await _transport.send('DELETE', query);
  }

  Future<List<LedgerTag>> fetchTags(int ledgerId) async {
    final data = await getJson('/api/tags?ledger=$ledgerId');
    final raw = data is Map<String, dynamic> ? data['tags'] : data;
    return raw is List
        ? raw
              .whereType<Map<String, dynamic>>()
              .map(LedgerTag.fromJson)
              .where((tag) => tag.name.isNotEmpty)
              .toList()
        : const [];
  }

  Future<void> renameTag({
    required int ledgerId,
    required String from,
    required String to,
  }) async {
    await patchJson('/api/tags', {
      'ledgerId': ledgerId,
      'from': from.trim(),
      'to': to.trim(),
    });
  }

  Future<void> deleteTag({required int ledgerId, required String name}) async {
    await deleteJson('/api/tags', {'ledgerId': ledgerId, 'name': name.trim()});
  }

  Future<Preferences> fetchPreferences() async {
    final data = await getJson('/api/preferences');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('隐私配置响应格式无效');
    }
    return Preferences.fromJson(data);
  }

  Future<void> updatePreferences({
    String? theme,
    String? mobileThemeMode,
    bool? highContrast,
    String? defaultCurrency,
    bool? enabled,
    String? pin,
    bool? hideAmounts,
    bool? hapticsEnabled,
    bool? continuousEntry,
    bool? expandedCategories,
    List<String>? homeModules,
  }) async {
    final body = <String, dynamic>{};
    if (theme != null) body['theme'] = theme;
    if (mobileThemeMode != null) body['mobileThemeMode'] = mobileThemeMode;
    if (highContrast != null) body['highContrast'] = highContrast;
    if (defaultCurrency != null) body['defaultCurrency'] = defaultCurrency;
    if (enabled != null) body['enabled'] = enabled;
    if (pin != null && pin.trim().isNotEmpty) body['pin'] = pin.trim();
    if (hideAmounts != null) body['hideAmounts'] = hideAmounts;
    if (hapticsEnabled != null) body['hapticsEnabled'] = hapticsEnabled;
    if (continuousEntry != null) body['continuousEntry'] = continuousEntry;
    if (expandedCategories != null) {
      body['expandedCategories'] = expandedCategories;
    }
    if (homeModules != null) body['homeModules'] = homeModules;
    await patchJson('/api/preferences', body);
  }

  Future<bool> verifyPreferencesPin(String pin) async {
    try {
      final data = await postJson('/api/preferences', {'pin': pin});
      return data is Map<String, dynamic> && data['ok'] == true;
    } on ApiException catch (error) {
      if (error.statusCode == 401 || error.statusCode == 403) return false;
      rethrow;
    }
  }

  Future<AiReply> askAi({
    required int ledgerId,
    required String message,
    required bool consentExternal,
  }) async {
    final data = await postJson(
      '/api/v1/ai/chat',
      {'ledgerId': ledgerId, 'message': message.trim()},
      extraHeaders: {'x-neo-ai-consent': consentExternal ? 'true' : 'false'},
    );
    if (data is! Map<String, dynamic>) throw const ApiException('AI 响应格式无效');
    return AiReply.fromJson(data);
  }

  Future<Map<String, dynamic>> recognizeScreenshotTextWithAi(
    String redactedText,
  ) async {
    final data = await postJson(
      '/api/v1/ai/screenshot-recognition',
      {'consent': true, 'text': redactedText},
      extraHeaders: const {'x-neo-ai-consent': 'true'},
    );
    if (data is! Map<String, dynamic> || data['suggestions'] is! Map) {
      throw const ApiException('截图 AI 识别响应格式无效');
    }
    return Map<String, dynamic>.from(data['suggestions'] as Map);
  }

  Future<Map<String, dynamic>> fetchMfaStatus() async {
    final data = await getJson('/api/auth/mfa');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('二次验证状态响应格式无效');
    }
    return data;
  }

  Future<Map<String, dynamic>> beginMfaSetup() async {
    final data = await postJson('/api/auth/mfa', {'action': 'begin'});
    if (data is! Map<String, dynamic> || data['secret'] is! String) {
      throw const ApiException('二次验证设置信息无效');
    }
    return data;
  }

  Future<Map<String, dynamic>> confirmMfaSetup(String code) async =>
      _mfaPost({'action': 'enable', 'code': code.trim()});

  Future<Map<String, dynamic>> regenerateMfaRecoveryCodes(String code) async =>
      _mfaPost({'action': 'regenerate-recovery', 'code': code.trim()});

  Future<Map<String, dynamic>> disableMfa(String code) async {
    final response = await _transport.send(
      'DELETE',
      '/api/auth/mfa',
      body: {'code': code.trim()},
    );
    final data = _transport.decodeAny(response);
    if (data is! Map<String, dynamic>) {
      throw const ApiException('关闭二次验证响应格式无效');
    }
    return data;
  }

  Future<Map<String, dynamic>> _mfaPost(Map<String, dynamic> body) async {
    final data = await postJson('/api/auth/mfa', body);
    if (data is! Map<String, dynamic>) {
      throw const ApiException('二次验证操作响应格式无效');
    }
    return data;
  }

  Future<Map<String, dynamic>> syncWebDav({
    required String action,
    required String url,
    required String username,
    required String password,
    String? payload,
  }) async {
    final body = <String, dynamic>{
      'action': action,
      'url': url.trim(),
      'username': username.trim(),
      'password': password,
    };
    if (payload != null) body['payload'] = payload;
    final data = await postJson('/api/webdav-sync', body);
    if (data is! Map<String, dynamic>) {
      throw const ApiException('WebDAV 响应格式无效');
    }
    return data;
  }

  Future<Map<String, dynamic>> fetchP2pStatus() async {
    final data = await getJson('/api/p2p/discovery');
    if (data is! Map<String, dynamic>) throw const ApiException('P2P 状态响应格式无效');
    return data;
  }

  Future<ExchangeRateSnapshot> fetchExchangeRates() async {
    final data = await getJson('/api/exchange-rates');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('汇率响应格式无效');
    }
    return ExchangeRateSnapshot.fromJson(data);
  }

  Future<List<AutomationRule>> fetchAutomationRules(int ledgerId) async {
    final data = await getJson('/api/automation/rules?ledger=$ledgerId');
    if (data is! List) throw const ApiException('自动化规则响应格式无效');
    return data
        .whereType<Map<String, dynamic>>()
        .map(AutomationRule.fromJson)
        .toList();
  }

  Future<void> createAutomationRule({
    required int ledgerId,
    required String name,
    required int priority,
    required bool enabled,
    required Map<String, dynamic> conditions,
    required Map<String, dynamic> actions,
  }) async {
    await postJson('/api/automation/rules', {
      'ledgerId': ledgerId,
      'name': name.trim(),
      'priority': priority,
      'enabled': enabled,
      'conditions': conditions,
      'actions': actions,
    });
  }

  Future<void> updateAutomationRule({
    required String id,
    required int ledgerId,
    String? name,
    int? priority,
    bool? enabled,
    Map<String, dynamic>? conditions,
    Map<String, dynamic>? actions,
  }) async {
    final body = <String, dynamic>{'id': id, 'ledgerId': ledgerId};
    if (name != null) body['name'] = name.trim();
    if (priority != null) body['priority'] = priority;
    if (enabled != null) body['enabled'] = enabled;
    if (conditions != null) body['conditions'] = conditions;
    if (actions != null) body['actions'] = actions;
    await patchJson('/api/automation/rules', body);
  }

  Future<void> deleteAutomationRule({
    required String id,
    required int ledgerId,
  }) async {
    await deleteJson('/api/automation/rules', {'id': id, 'ledgerId': ledgerId});
  }

  Future<QuickSyncStatus> fetchQuickSyncStatus() async {
    final data = await getJson('/api/integrations/quick-sync');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('快捷同步响应格式无效');
    }
    return QuickSyncStatus.fromJson(data);
  }

  Future<String> createQuickSyncToken({
    required String label,
    required int expiresInDays,
    required String scope,
  }) async {
    final data = await postJson('/api/integrations/quick-sync', {
      'label': label.trim(),
      'expiresInDays': expiresInDays,
      'scope': scope,
    });
    if (data is Map<String, dynamic> && data['token'] is String) {
      final token = (data['token'] as String).trim();
      if (token.isNotEmpty) return token;
    }
    throw const ApiException('快捷同步未返回一次性密钥');
  }

  Future<void> revokeQuickSyncToken() async {
    await _transport.send('DELETE', '/api/integrations/quick-sync');
  }

  Future<List<SecuritySession>> fetchSecuritySessions() async {
    final data = await getJson('/api/security/sessions');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('登录会话响应格式无效');
    }
    return (data['sessions'] as List<dynamic>? ?? const [])
        .whereType<Map<String, dynamic>>()
        .map(SecuritySession.fromJson)
        .toList();
  }

  Future<void> revokeSecuritySession({
    String? sessionId,
    bool allExceptCurrent = false,
  }) async {
    final body = <String, dynamic>{};
    if (sessionId != null && sessionId.trim().isNotEmpty) {
      body['sessionId'] = sessionId.trim();
    } else if (allExceptCurrent) {
      body['allExceptCurrent'] = true;
    } else {
      throw const ApiException('缺少要撤销的会话');
    }
    await deleteJson('/api/security/sessions', body);
  }

  Future<SecurityAuditPage> fetchSecurityAudit() async {
    final data = await getJson('/api/security/audit?limit=100');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('安全审计响应格式无效');
    }
    return SecurityAuditPage.fromJson(data);
  }

  Future<Member> createMember({
    required int ledgerId,
    required String name,
    required String icon,
  }) async {
    final data = await postJson('/api/members', {
      'ledgerId': ledgerId,
      'name': name.trim(),
      'icon': icon.trim().isEmpty ? '👤' : icon.trim(),
    });
    if (data is! Map<String, dynamic>) throw const ApiException('参与人响应格式无效');
    return Member.fromJson(data);
  }

  Future<void> settleMember({
    required int ledgerId,
    required int memberId,
    required double amount,
    required String direction,
    String? idempotencyKey,
  }) async {
    final payload = {
      'ledgerId': ledgerId,
      'memberId': memberId,
      'amount': (amount * 100).round(),
      'direction': direction,
    };
    await _idempotencyKeys.run(
      operation: 'native-settlement',
      request: payload,
      idempotencyKey: idempotencyKey,
      send: (key) =>
          postJson('/api/settlements', {...payload, 'idempotencyKey': key}),
    );
  }

  Future<void> saveFireSettings({
    required int ledgerId,
    required double monthlyExpense,
    required double annualReturn,
  }) async {
    await putJson('/api/fire-settings', {
      'ledgerId': ledgerId,
      'monthlyExpense': monthlyExpense,
      'annualReturn': annualReturn,
    });
  }

  Future<Map<String, dynamic>> fetchFireSettings(int ledgerId) async {
    final data = await getJson('/api/fire-settings?ledger=$ledgerId');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('FIRE 参数响应格式无效');
    }
    return data;
  }

  Future<void> saveEconomicSettings({
    required int ledgerId,
    required double inflationRate,
  }) async {
    await putJson('/api/economic-settings', {
      'ledgerId': ledgerId,
      'inflationRate': inflationRate,
    });
  }

  Future<Map<String, dynamic>> fetchEconomicSettings(int ledgerId) async {
    final data = await getJson('/api/economic-settings?ledger=$ledgerId');
    if (data is! Map<String, dynamic>) {
      throw const ApiException('经济参数响应格式无效');
    }
    return data;
  }

  Future<void> saveAccount({
    int? id,
    required int ledgerId,
    required String name,
    required String type,
    required double balance,
    int? billDay,
    int? repaymentDay,
    required bool isInvestment,
    required String currency,
    required String assetClass,
    bool? isActive,
    String? expectedUpdatedAt,
  }) async {
    final body = <String, dynamic>{
      'ledgerId': ledgerId,
      'name': name.trim(),
      'type': type,
      'balance': balance,
      'billDay': billDay,
      'repaymentDay': repaymentDay,
      'isInvestment': isInvestment,
      'currency': currency,
      'assetClass': assetClass,
    };
    if (id == null) {
      await postJson('/api/accounts', body);
      return;
    }
    body['id'] = id;
    if (isActive != null) body['isActive'] = isActive;
    body['expectedUpdatedAt'] = expectedUpdatedAt;
    await putJson('/api/accounts', body);
  }

  Future<void> reorderAccounts({
    required int ledgerId,
    required List<int> accountIds,
  }) async {
    await postJson('/api/accounts/reorder', {
      'ledgerId': ledgerId,
      'accountIds': accountIds,
    });
  }

  Future<void> deleteAccount({
    required int id,
    required String expectedUpdatedAt,
  }) async {
    final path = Uri(
      path: '/api/accounts',
      queryParameters: {'id': '$id', 'expectedUpdatedAt': expectedUpdatedAt},
    ).toString();
    await _transport.send('DELETE', path);
  }

  Future<void> transfer({
    required int ledgerId,
    required String kind,
    required int fromAccountId,
    required int toAccountId,
    required double amount,
    required String occurredAt,
    required String originalTimezone,
    String? note,
    String? idempotencyKey,
  }) async {
    final payload = {
      'ledgerId': ledgerId,
      'kind': kind,
      'fromAccountId': fromAccountId,
      'toAccountId': toAccountId,
      'amount': amount,
      'occurredAt': occurredAt,
      'originalTimezone': originalTimezone,
      if (note != null && note.trim().isNotEmpty) 'note': note.trim(),
    };
    await _idempotencyKeys.run(
      operation: 'native-transfer',
      request: payload,
      idempotencyKey: idempotencyKey,
      send: (key) =>
          postJson('/api/transfers', {...payload, 'idempotencyKey': key}),
    );
  }

  Future<TransactionPage> fetchTransactions(
    int ledgerId, {
    int limit = 50,
    String? query,
    String? from,
    String? to,
    String? cursor,
    int? id,
    int? accountId,
    String? type,
    String? category,
    double? minAmount,
    double? maxAmount,
    int timezoneOffsetMinutes = 0,
  }) async {
    final parameters = <String, String>{
      'ledger': '$ledgerId',
      'limit': '${limit.clamp(1, 100)}',
      'offset': '$timezoneOffsetMinutes',
      if (query != null && query.trim().isNotEmpty) 'q': query.trim(),
      'from': ?from,
      'to': ?to,
      'cursor': ?cursor,
      if (id != null) 'id': '$id',
      if (accountId != null) 'accountId': '$accountId',
      if (type != null && type.isNotEmpty) 'type': type,
      if (category != null && category.isNotEmpty) 'category': category,
      if (minAmount != null) 'minAmount': '$minAmount',
      if (maxAmount != null) 'maxAmount': '$maxAmount',
    };
    final path = Uri(
      path: '/api/transactions/query',
      queryParameters: parameters,
    ).toString();
    final data = await getJson(path);
    if (data is! Map<String, dynamic>) throw const ApiException('流水响应格式无效');
    return TransactionPage.fromJson(data);
  }

  /// Cheap change probe used by native clients before refreshing shared data.
  Future<String> fetchLedgerSyncRevision(int ledgerId) async {
    try {
      final data = await getJson('/api/sync/revision?ledger=$ledgerId');
      if (data is! Map<String, dynamic>) {
        throw const ApiException('账本同步标记响应格式无效');
      }
      return '${data['revision'] ?? '0'}';
    } catch (_) {
      // Older self-hosted servers expose only transaction revisions. The
      // periodic full refresh remains the compatibility safety net there.
      final legacy = await getJson(
        '/api/transactions/revision?ledger=$ledgerId',
      );
      if (legacy is! Map<String, dynamic>) {
        throw const ApiException('账本同步标记响应格式无效');
      }
      return 'legacy:${legacy['revision'] ?? '0'}:${legacy['updatedAt'] ?? ''}';
    }
  }

  Future<AnalysisSummary> fetchAnalysis(
    int ledgerId, {
    String dimension = '月',
  }) async {
    final now = DateTime.now();
    final today =
        '${now.year.toString().padLeft(4, '0')}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';
    final query = [
      'ledger=$ledgerId',
      'today=$today',
      'dimension=${Uri.encodeQueryComponent(dimension)}',
      'offset=${now.timeZoneOffset.inMinutes}',
      'hour=${now.hour}',
      'now=${Uri.encodeQueryComponent(now.toUtc().toIso8601String())}',
    ].join('&');
    final data = await getJson('/api/transactions/summary?$query');
    if (data is! Map<String, dynamic>) throw const ApiException('分析响应格式无效');
    return AnalysisSummary.fromJson(data);
  }

  Future<List<CategoryBudget>> fetchBudgets(int ledgerId) async {
    final now = DateTime.now();
    final today =
        '${now.year.toString().padLeft(4, '0')}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';
    final data = await getJson(
      '/api/category-budgets?ledger=$ledgerId&today=$today&offset=${now.timeZoneOffset.inMinutes}',
    );
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(CategoryBudget.fromJson)
              .toList()
        : const [];
  }

  Future<void> saveCategoryBudget({
    required int ledgerId,
    required String category,
    required double amount,
    bool? carryoverEnabled,
  }) async {
    await putJson('/api/category-budgets', {
      'ledgerId': ledgerId,
      'category': category.trim(),
      'amount': amount,
      ...?carryoverEnabled == null
          ? null
          : {'carryoverEnabled': carryoverEnabled},
    });
  }

  Future<List<Subscription>> fetchSubscriptions(int ledgerId) async {
    final data = await getJson('/api/subscriptions?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(Subscription.fromJson)
              .toList()
        : const [];
  }

  Future<List<RecurringTask>> fetchRecurringTasks(int ledgerId) async {
    final data = await getJson('/api/recurring-tasks?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(RecurringTask.fromJson)
              .toList()
        : const [];
  }

  Future<void> saveRecurringTask({
    int? id,
    required int ledgerId,
    required String name,
    required double amount,
    required String type,
    required int accountId,
    required String cycle,
    required String category,
    required String nextRunDate,
    required int reminderDays,
  }) async {
    final body = <String, dynamic>{
      'ledgerId': ledgerId,
      'name': name.trim(),
      'amount': amount,
      'type': type,
      'accountId': accountId,
      'cycle': cycle,
      'category': category.trim(),
      'nextRunDate': nextRunDate,
      'reminderDays': reminderDays,
    };
    if (id == null) {
      await postJson('/api/recurring-tasks', body);
    } else {
      body['id'] = id;
      await putJson('/api/recurring-tasks', body);
    }
  }

  Future<void> deleteRecurringTask({
    required int id,
    required int ledgerId,
  }) async {
    final path = Uri(
      path: '/api/recurring-tasks',
      queryParameters: {'id': '$id', 'ledger': '$ledgerId'},
    ).toString();
    await _transport.send('DELETE', path);
  }

  Future<void> setRecurringTaskPaused({
    required int id,
    required int ledgerId,
    required bool paused,
  }) async {
    await patchJson('/api/recurring-tasks', {
      'id': id,
      'ledgerId': ledgerId,
      'paused': paused,
    });
  }

  Future<List<Installment>> fetchInstallments(int ledgerId) async {
    final data = await getJson('/api/installments?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(Installment.fromJson)
              .toList()
        : const [];
  }

  Future<List<SavingsGoal>> fetchSavingsGoals(int ledgerId) async {
    final data = await getJson('/api/savings-goals?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(SavingsGoal.fromJson)
              .toList()
        : const [];
  }

  Future<Forecast> fetchForecast(int ledgerId) async {
    final data = await getJson('/api/forecast?ledger=$ledgerId');
    if (data is! Map<String, dynamic>) throw const ApiException('现金流预测响应格式无效');
    return Forecast.fromJson(data);
  }

  Future<List<DigitalAsset>> fetchAssets(int ledgerId) async {
    final data = await getJson('/api/assets?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(DigitalAsset.fromJson)
              .toList()
        : const [];
  }

  Future<void> saveAsset({
    int? id,
    required int ledgerId,
    required String name,
    required String assetType,
    required String currency,
    required String valuationMode,
    required double manualValue,
    required double purchasePrice,
    required String purchaseDate,
    required int lifespanMonths,
    required double residualRate,
    String? heatLevel,
    String? expectedUpdatedAt,
  }) async {
    final body = <String, dynamic>{
      'ledgerId': ledgerId,
      'name': name.trim(),
      'assetType': assetType,
      'currency': currency,
      'valuationMode': valuationMode,
      'manualValue': manualValue,
      'purchasePrice': purchasePrice,
      'purchaseDate': purchaseDate,
      'lifespanMonths': lifespanMonths,
      'residualRate': residualRate,
    };
    if (heatLevel != null) body['heatLevel'] = heatLevel;
    if (id != null) body['id'] = id;
    if (expectedUpdatedAt != null) {
      body['expectedUpdatedAt'] = expectedUpdatedAt;
    }
    if (id == null) {
      await postJson('/api/assets', body);
    } else {
      await putJson('/api/assets', body);
    }
  }

  Future<void> liquidateAsset({
    required int id,
    required int ledgerId,
    required double salePrice,
    required int accountId,
    required String expectedUpdatedAt,
    String? idempotencyKey,
  }) async {
    final payload = {
      'id': id,
      'ledgerId': ledgerId,
      'salePrice': salePrice,
      'accountId': accountId,
      'expectedUpdatedAt': expectedUpdatedAt,
    };
    await _idempotencyKeys.run(
      operation: 'native-liquidation',
      request: payload,
      idempotencyKey: idempotencyKey,
      send: (key) =>
          patchJson('/api/assets', {...payload, 'idempotencyKey': key}),
    );
  }

  Future<void> saveSubscription({
    int? id,
    required int ledgerId,
    required String name,
    required double amount,
    required int accountId,
    required String cycle,
    required String category,
    required String nextChargeDate,
  }) async {
    final body = <String, dynamic>{
      'ledgerId': ledgerId,
      'name': name.trim(),
      'amount': amount,
      'accountId': accountId,
      'cycle': cycle,
      'category': category.trim(),
      'nextChargeDate': nextChargeDate,
    };
    if (id == null) {
      await postJson('/api/subscriptions', body);
    } else {
      body['id'] = id;
      await putJson('/api/subscriptions', body);
    }
  }

  Future<void> deleteSubscription({
    required int id,
    required int ledgerId,
  }) async {
    final path = Uri(
      path: '/api/subscriptions',
      queryParameters: {'id': '$id', 'ledger': '$ledgerId'},
    ).toString();
    await _transport.send('DELETE', path);
  }

  Future<void> setSubscriptionPaused({
    required int id,
    required int ledgerId,
    required bool paused,
  }) async {
    await patchJson('/api/subscriptions', {
      'id': id,
      'ledgerId': ledgerId,
      'paused': paused,
    });
  }

  Future<void> createInstallment({
    required int ledgerId,
    required String name,
    required double totalAmount,
    required int periods,
    required double feeAmount,
    required int accountId,
    required int paymentAccountId,
    required String startMonth,
    required int chargeDay,
    String? idempotencyKey,
  }) async {
    final payload = {
      'ledgerId': ledgerId,
      'name': name.trim(),
      'totalAmount': totalAmount,
      'periods': periods,
      'feeAmount': feeAmount,
      'accountId': accountId,
      'paymentAccountId': paymentAccountId,
      'startMonth': startMonth,
      'chargeDay': chargeDay,
    };
    await _idempotencyKeys.run(
      operation: 'native-installment',
      request: payload,
      idempotencyKey: idempotencyKey,
      send: (key) =>
          postJson('/api/installments', {...payload, 'idempotencyKey': key}),
    );
  }

  Future<void> deleteInstallment({
    required int id,
    required String expectedUpdatedAt,
    String? idempotencyKey,
  }) async {
    final payload = {'id': id, 'expectedUpdatedAt': expectedUpdatedAt};
    await _idempotencyKeys.run(
      operation: 'native-installment-delete',
      request: payload,
      idempotencyKey: idempotencyKey,
      send: (key) {
        final path = Uri(
          path: '/api/installments',
          queryParameters: {
            'id': '$id',
            'expectedUpdatedAt': expectedUpdatedAt,
            'idempotencyKey': key,
          },
        ).toString();
        return _transport.send('DELETE', path);
      },
    );
  }

  Future<void> createSavingsGoal({
    required int ledgerId,
    required String name,
    required double targetAmount,
    required String deadline,
    required String icon,
  }) async {
    await postJson('/api/savings-goals', {
      'ledgerId': ledgerId,
      'name': name.trim(),
      'targetAmount': targetAmount,
      'deadline': deadline,
      'icon': icon.trim().isEmpty ? '🌟' : icon.trim(),
    });
  }

  Future<void> contributeSavingsGoal({
    required int id,
    required int accountId,
    required double amount,
    String? idempotencyKey,
  }) async {
    final payload = {'id': id, 'accountId': accountId, 'amount': amount};
    await _idempotencyKeys.run(
      operation: 'native-goal-contribution',
      request: payload,
      idempotencyKey: idempotencyKey,
      send: (key) =>
          patchJson('/api/savings-goals', {...payload, 'idempotencyKey': key}),
    );
  }

  Future<void> deleteSavingsGoal({
    required int id,
    required int accountId,
    required String expectedUpdatedAt,
    String? idempotencyKey,
  }) async {
    final payload = {
      'id': id,
      'accountId': accountId,
      'expectedUpdatedAt': expectedUpdatedAt,
    };
    await _idempotencyKeys.run(
      operation: 'native-goal-delete',
      request: payload,
      idempotencyKey: idempotencyKey,
      send: (key) =>
          deleteJson('/api/savings-goals', {...payload, 'idempotencyKey': key}),
    );
  }

  Future<List<NotificationItem>> fetchNotifications(int ledgerId) async {
    final data = await getJson('/api/notifications?ledger=$ledgerId');
    return data is List
        ? data
              .whereType<Map<String, dynamic>>()
              .map(NotificationItem.fromJson)
              .toList()
        : const [];
  }

  Future<PendingTransactionPage> fetchPendingTransactions(int ledgerId) async {
    final response = await _transport.send(
      'GET',
      '/api/pending-transactions?ledger=$ledgerId&limit=100',
    );
    final data = _transport.decodeAny(response);
    if (data is! Map<String, dynamic>) {
      throw const ApiException('待处理账单响应格式无效');
    }
    return PendingTransactionPage(
      items: (data['items'] as List<dynamic>? ?? const [])
          .whereType<Map<String, dynamic>>()
          .map(PendingTransaction.fromJson)
          .toList(),
      total:
          int.tryParse(response.headers['x-total-count'] ?? '') ??
          int.tryParse('${data['total'] ?? 0}') ??
          0,
      hasMore:
          response.headers['x-has-more'] == 'true' || data['hasMore'] == true,
    );
  }

  Future<void> markNotificationsRead(int ledgerId) async {
    await patchJson('/api/notifications', {'ledgerId': ledgerId});
  }

  Future<void> resolvePendingTransaction(
    int id, {
    required String action,
    String? category,
  }) async {
    await patchJson('/api/pending-transactions', {
      'id': id,
      'action': action,
      if (category != null && category.trim().isNotEmpty)
        'category': category.trim(),
    });
  }

  Future<void> updateTransaction(
    TransactionItem item, {
    required String title,
    required double amount,
    required String type,
    required int accountId,
    required String category,
    String? mood,
    String? note,
    List<String> tags = const [],
    bool reimbursable = false,
    int discountAmountCents = 0,
    bool excludeFromBudget = false,
  }) async {
    if (item.ledgerId <= 0 || item.updatedAt == null) {
      throw const ApiException('流水缺少版本信息，请刷新后再编辑');
    }
    final occurred = DateTime.tryParse(item.occurredAt)?.toLocal();
    if (occurred == null) throw const ApiException('流水时间格式无效');
    final localDate = DateFormat("yyyy-MM-dd'T'HH:mm").format(occurred);
    await putJson('/api/transactions', {
      'id': item.id,
      'ledgerId': item.ledgerId,
      'accountId': accountId,
      'amount': amount,
      'type': type,
      'title': title,
      if (note != null && note.trim().isNotEmpty) 'note': note.trim(),
      if (tags.isNotEmpty) 'tags': tags,
      'reimbursable': reimbursable,
      'discountAmount': discountAmountCents / 100,
      'excludeFromBudget': excludeFromBudget,
      'mood': mood ?? item.mood ?? '刚需',
      'category': type == '支出' ? category : '其它',
      'incomeCategory': type == '收入' ? category : '其它收入',
      'occurredAt': localDate,
      'originalTimezone': item.originalTimezone,
      'expectedUpdatedAt': item.updatedAt,
    });
  }

  Future<Map<String, dynamic>> previewBillImport({
    required int ledgerId,
    required List<Map<String, dynamic>> items,
  }) async {
    final data = await postJson('/api/bill-import', {
      'ledgerId': ledgerId,
      'items': items,
    });
    if (data is! Map<String, dynamic>) throw const ApiException('账单预检响应格式无效');
    return data;
  }

  Future<Map<String, dynamic>> importBills({
    required int ledgerId,
    required List<Map<String, dynamic>> items,
  }) async {
    final data = await putJson('/api/bill-import', {
      'ledgerId': ledgerId,
      'items': items,
    });
    if (data is! Map<String, dynamic>) throw const ApiException('账单导入响应格式无效');
    return data;
  }

  Future<String?> deleteTransaction(TransactionItem item) async {
    if (item.ledgerId <= 0 || item.updatedAt == null) {
      throw const ApiException('流水缺少版本信息，请刷新后再删除');
    }
    final data = await deleteJson('/api/transactions', {
      'id': item.id,
      'ledgerId': item.ledgerId,
      'expectedUpdatedAt': item.updatedAt,
    });
    return data is Map<String, dynamic> ? data['undoToken'] as String? : null;
  }

  Future<void> restoreTransaction({
    required int ledgerId,
    required String undoToken,
  }) async {
    await postJson('/api/transactions/restore', {
      'ledgerId': ledgerId,
      'undoToken': undoToken,
    });
  }

  Future<void> bulkUpdateTransactions({
    required int ledgerId,
    required List<int> transactionIds,
    String? category,
    String? incomeCategory,
    String? mood,
    List<String>? tags,
    bool? reimbursable,
    bool? excludeFromBudget,
  }) async {
    final payload = <String, dynamic>{
      'ledgerId': ledgerId,
      'transactionIds': transactionIds,
    };
    if (category != null && category.trim().isNotEmpty) {
      payload['category'] = category.trim();
    }
    if (incomeCategory != null && incomeCategory.trim().isNotEmpty) {
      payload['incomeCategory'] = incomeCategory.trim();
    }
    if (mood != null && mood.trim().isNotEmpty) payload['mood'] = mood.trim();
    if (tags != null) payload['tags'] = tags;
    if (reimbursable != null) payload['reimbursable'] = reimbursable;
    if (excludeFromBudget != null) {
      payload['excludeFromBudget'] = excludeFromBudget;
    }
    await postJson('/api/transactions/bulk', payload);
  }

  Future<List<String>> syncEntries(List<OfflineEntry> entries) async {
    if (entries.isEmpty) return const [];
    final data = await postJson('/api/offline-sync', {
      'items': entries.map((entry) => entry.toJson()).toList(),
    });
    if (data is! Map<String, dynamic>) throw const ApiException('同步响应格式无效');
    return (data['synced'] as List<dynamic>? ?? const [])
        .map((value) => '$value')
        .toList();
  }

  /// Exports the complete server-side backup as the JSON document produced by
  /// `/api/data/export`. Keeping the raw document lets the native client pass
  /// it back to the restore endpoint without losing fields added by the web
  /// client in a newer backup schema.
  Future<String> exportBackup() async {
    final response = await _transport.send('GET', '/api/data/export');
    return utf8.decode(response.bodyBytes);
  }

  /// Runs the server's validation-only or actual restore flow.
  Future<Map<String, dynamic>> restoreBackup(
    String rawBackup, {
    required bool dryRun,
    String? expectedPlanChecksum,
  }) async {
    final decoded = jsonDecode(rawBackup);
    if (decoded is! Map) throw const ApiException('备份必须是 JSON 对象');
    final body = Map<String, dynamic>.from(decoded);
    body['dryRun'] = dryRun;
    final response = await _transport.send(
      'POST',
      '/api/data/restore',
      body: body,
      extraHeaders: {
        if (expectedPlanChecksum != null && expectedPlanChecksum.isNotEmpty)
          'x-restore-plan-checksum': expectedPlanChecksum,
      },
    );
    final data = _transport.decodeAny(response);
    if (data is! Map<String, dynamic>) {
      throw const ApiException('恢复响应格式无效');
    }
    return data;
  }

  Future<dynamic> getJson(String path) async =>
      _transport.decodeAny(await _transport.send('GET', path));

  Future<dynamic> postJson(
    String path,
    Map<String, dynamic> body, {
    Map<String, String>? extraHeaders,
  }) async => _transport.decodeAny(
    await _transport.send('POST', path, body: body, extraHeaders: extraHeaders),
  );

  Future<dynamic> putJson(String path, Map<String, dynamic> body) async =>
      _transport.decodeAny(await _transport.send('PUT', path, body: body));

  Future<dynamic> patchJson(String path, Map<String, dynamic> body) async =>
      _transport.decodeAny(await _transport.send('PATCH', path, body: body));

  Future<dynamic> deleteJson(String path, Map<String, dynamic> body) async =>
      _transport.decodeAny(await _transport.send('DELETE', path, body: body));

  Future<void> logout() => _session.logout();
}
